### ISSUE TITLE
Prepare list of questions for Elena of Macrosynergy

### ISSUE THREAD

**Issue by alexr-seven** [alexr-seven/data-science-capstone#7]

**Comment by alexr-seven** [comment]
Can you please share a list of all available variables along with their frequency?

Do you have any recommended resources you can share for getting acquainted with the platform/available data?

Can you please advise on the process for us to get direct access so that we don't have to take up as much of your time requesting data extracts?

Are you able to recommend factors which may prove valueable to investigate, and which are not available in Bloomberg?

**Comment by dalalkamal** [comment]
Data availability at individual stock level, or Index level? Do you have sector level information? 

Which countries are covered? 

Any data on Geopolitical threats? 

Which commodities are covered?
